#!/bin/sh
set -eux

# Add sociomantic-tsunami mxnet APT repo
dist="$(lsb_release -cs)"
echo "deb https://dl.bintray.com/sociomantic-tsunami/mxnet $dist release" \
    >> /etc/apt/sources.list.d/mxnet.list

# Update already-installed packages
apt-get update
apt-get -y upgrade

# Install dmxnet dependencies
apt-get install -y \
    libmxnet \
    zlib1g-dev
