#!/bin/sh
set -eux

# Update essential packages
apt-get update
apt-get -y upgrade

# Add sociomantic-tsunami APT repos
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
echo '# sociomantic-tsunami repos' \
    > /etc/apt/sources.list.d/sociomantic-tsunami.list
dist="$(lsb_release -cs)"
echo "deb https://dl.bintray.com/sociomantic-tsunami/mxnet $dist release" \
    >> /etc/apt/sources.list.d/sociomantic-tsunami.list
apt-get update

# Install dmxnet dependencies
apt-get install -y \
    libmxnet
