#!/bin/sh

set -eu

download_dir=${1-${MNIST_DATA_DIR-"${HOME}/.cache/mnist"}}

base_url="http://yann.lecun.com/exdb/mnist"

mnist_sha256sums=$(cat <<EOT
8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6  t10k-images-idx3-ubyte.gz
f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6  t10k-labels-idx1-ubyte.gz
440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609  train-images-idx3-ubyte.gz
3552534a0a558bbed6aed32b30c495cca23d567ec52cac8be1a0730e8010255c  train-labels-idx1-ubyte.gz
EOT
)

mkdir -p "${download_dir}"
cd "${download_dir}"
echo "${mnist_sha256sums}" | cut -d' ' -f3 | xargs -I% wget -nv -nc "${base_url}/%"
echo "${mnist_sha256sums}" | sha256sum --quiet --strict -c
